laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('institucional', 'InstitucionalController@index')->name('institucional');
    Route::get('escopo-de-negocios', 'EscopoDeNegociosController@index')->name('escopo-de-negocios');
    Route::get('produtos-e-solucoes', 'ProdutosController@index')->name('produtos');
    Route::get('obras-executadas', 'ObrasExecutadasController@index')->name('obras-executadas');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@envio')->name('contato.envio');


    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function() {
        Route::get('/', 'PainelController@index')->name('painel');

        /* GENERATED ROUTES */
		Route::resource('home', 'HomeController');
        Route::resource('produtos', 'ProdutosCategoriasController');
        Route::resource('produtos.subcategorias', 'ProdutosSubcategoriasController');
		Route::resource('produtos.subcategorias.itens', 'ProdutosItensController');
		Route::resource('obras-executadas', 'ObrasExecutadasController');
		Route::resource('escopo-de-negocios', 'EscopoDeNegociosController');
		Route::resource('institucional', 'InstitucionalController', ['only' => ['index', 'update']]);
		Route::resource('banners', 'BannersController');
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::resource('usuarios', 'UsuariosController');

        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function() {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Http/Controllers/ProdutosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

use App\Models\ProdutoCategoria;

class ProdutosController extends Controller
{
    public function index(Request $request)
    {
        $categorias = ProdutoCategoria::ordenados()->get();
        $selecao    = $request->has('cat') ? (int)$request->get('cat') : 0;

        return view('frontend.produtos', compact('categorias', 'selecao'));
    }
}

laravel/resources/views/painel/produtos/itens/create.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Produtos / {{ $categoria->titulo }} / {{ $subcategoria->titulo }} /</small> Adicionar Item</h2>
    </legend>

    {!! Form::open(['route' => ['painel.produtos.subcategorias.itens.store', $categoria->id, $subcategoria->id], 'files' => true]) !!}

        @include('painel.produtos.itens.form', ['submitText' => 'Inserir'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/produtos/itens/edit.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Produtos / {{ $categoria->titulo }} / {{ $subcategoria->titulo }} /</small> Editar Item</h2>
    </legend>

    {!! Form::model($registro, [
        'route'  => ['painel.produtos.subcategorias.itens.update', $categoria->id, $subcategoria->id, $registro->id],
        'method' => 'patch',
        'files'  => true])
    !!}

    @include('painel.produtos.itens.form', ['submitText' => 'Alterar'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/produtos/itens/form.blade.php
@include('painel.common.flash')

<div class="form-group">
    {!! Form::label('titulo', 'Título') !!}
    {!! Form::text('titulo', null, ['class' => 'form-control']) !!}
</div>

<div class="well form-group">
    {!! Form::label('imagem', 'Imagem') !!}
@if($submitText == 'Alterar')
    <img src="{{ url('assets/img/produtos/'.$registro->imagem) }}" style="display:block; margin-bottom: 10px; max-width: 100%">
@endif
    {!! Form::file('imagem', ['class' => 'form-control']) !!}
</div>

{!! Form::submit($submitText, ['class' => 'btn btn-success']) !!}

<a href="{{ route('painel.produtos.subcategorias.itens.index', [$categoria->id, $subcategoria->id]) }}" class="btn btn-default btn-voltar">Voltar</a>

laravel/resources/views/painel/produtos/itens/index.blade.php
@extends('painel.common.template')

@section('content')

    @include('painel.common.flash')

    <a href="{{ route('painel.produtos.subcategorias.index', $categoria->id, $subcategoria->id) }}" class="btn btn-sm btn-default">
        &larr; Voltar para Subcategorias
    </a>

    <legend>
        <h2>
            <small>Produtos / {{ $categoria->titulo }} / {{ $subcategoria->titulo }} /</small> Itens
            <a href="{{ route('painel.produtos.subcategorias.itens.create', [$categoria->id, $subcategoria->id]) }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>Adicionar Item</a>
        </h2>
    </legend>

    @if(!count($registros))
    <div class="alert alert-warning" role="alert">Nenhum registro encontrado.</div>
    @else
    <table class="table table-striped table-bordered table-hover table-info table-sortable" data-table="produtos_itens">
        <thead>
            <tr>
                <th>Ordenar</th>
                <th>Título</th>
                <th>Imagem</th>
                <th class="no-filter"><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($registros as $registro)
            <tr class="tr-row" id="{{ $registro->id }}">
                <td>
                    <a href="#" class="btn btn-info btn-sm btn-move">
                        <span class="glyphicon glyphicon-move"></span>
                    </a>
                </td>
                <td>{{ $registro->titulo }}</td>
                <td><img src="{{ asset('assets/img/produtos/'.$registro->imagem) }}" style="width: 100%; max-width:150px;" alt=""></td>
                <td class="crud-actions">
                    {!! Form::open([
                        'route'  => ['painel.produtos.subcategorias.itens.destroy', $categoria->id, $subcategoria->id, $registro->id],
                        'method' => 'delete'
                    ]) !!}

                    <div class="btn-group btn-group-sm">
                        <a href="{{ route('painel.produtos.subcategorias.itens.edit', [$categoria->id, $subcategoria->id, $registro->id] ) }}" class="btn btn-primary btn-sm pull-left">
                            <span class="glyphicon glyphicon-pencil" style="margin-right:10px;"></span>Editar
                        </a>

                        <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                    </div>

                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>


    @endif

@endsection